### ISSUE TITLE
Broken OUI update

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/profiler#163]
**Describe the bug**
OUI update is broke

**To Reproduce**
`sudo profiler --oui_update`

**Debug output**
```bash
sudo profiler --oui_update
2023-07-28 11:07:53,056 [INFO] update_manuf: OUI database is located at /opt/wlanpi-profiler/lib/python3.9/site-packages/manuf/manuf
2023-07-28 11:07:53,057 [INFO] update_manuf: manuf is located at /opt/wlanpi-profiler/bin/manuf
2023-07-28 11:07:53,057 [INFO] update_manuf: manuf file last modified at: Tue Sep 20 22:59:30 2022
2023-07-28 11:07:53,057 [INFO] update_manuf: running 'sudo manuf --update'
2023-07-28 11:07:53,769 [INFO] update_manuf: Traceback (most recent call last):
  File "/opt/wlanpi-profiler/lib/python3.9/site-packages/manuf/manuf.py", line 144, in update
    response = urlopen(Request(manuf_url, headers={'User-Agent': 'Mozilla'}))
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/wlanpi-profiler/bin/manuf", line 8, in <module>
    sys.exit(main())
  File "/opt/wlanpi-profiler/lib/python3.9/site-packages/manuf/manuf.py", line 324, in main
    parser = MacParser(manuf_name=args.manuf, update=args.update)
  File "/opt/wlanpi-profiler/lib/python3.9/site-packages/manuf/manuf.py", line 70, in __init__
    self.update()
  File "/opt/wlanpi-profiler/lib/python3.9/site-packages/manuf/manuf.py", line 146, in update
    raise URLError("Failed downloading OUI database")
urllib.error.URLError: <urlopen error Failed downloading OUI database>
```

**Comment by joshschmelzle** [comment]
manuf update URL 404s now https://github.com/coolbho3k/manuf/blob/d1e492266d4af4cbed1f9b06fa2dd8fea2c1b31c/manuf/manuf.py#L64C74-L64C74

**Comment by joshschmelzle** [comment]
Wireshark replaced their `manuf` file to reduce start up time which broke our dependency for `--oui-update`. https://gitlab.com/wireshark/wireshark/-/commit/b4a421cf8206dc9a675fbc58500d1a625869e77a
