### ISSUE TITLE
Profiler fails to compile BPF filters on WLAN Pi 2.1.2

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/profiler#173]
**Describe the bug**

Profiler fails to launch and throws a scapy exception:

```bash
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req or type mgt subtype auth or type mgt subtype assoc-req or type mgt subtype reassoc-req (-1)
```

**To Reproduce**

Steps to reproduce the issue.

Launch profiler like `sudo profiler` from a WLAN Pi terminal running 2.1.2. 

**Expected behavior**

Profiler shouldn't crash.

**Debug output**

```bash
wlanpi@wlanpi:~$ sudo profiler
[sudo] password for wlanpi:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting a fake AP using wlan0mon on channel 36 (5180)

Getting started:

 - Associate your Wi-Fi client to *our* SSID: WLAN Pi
 - Enter any random password to connect
 - Authentication will fail, which is OK
 - We should receive an association request to 78:d2:94:2c:05:47
 - Results are then saved locally and printed on the shell
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2023-11-08 15:42:51,151 [INFO] fakeap.py: starting beacon transmissions
2023-11-08 15:42:51,409 [ERROR] fakeap.py: we had a problem creating BPF filters on L2socket/wlan0mon
Traceback (most recent call last):
  File "/opt/wlanpi/pipx/venvs/profiler/lib/python3.9/site-packages/profiler/fakeap.py", line 385, in __init__
    sniff(
  File "/opt/wlanpi/pipx/venvs/profiler/lib/python3.9/site-packages/scapy/sendrecv.py", line 1263, in sniff
    sniffer._run(*args, **kwargs)
  File "/opt/wlanpi/pipx/venvs/profiler/lib/python3.9/site-packages/scapy/sendrecv.py", line 1127, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/opt/wlanpi/pipx/venvs/profiler/lib/python3.9/site-packages/scapy/arch/linux.py", line 497, in __init__
    attach_filter(self.ins, filter, self.iface)
  File "/opt/wlanpi/pipx/venvs/profiler/lib/python3.9/site-packages/scapy/arch/linux.py", line 166, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/opt/wlanpi/pipx/venvs/profiler/lib/python3.9/site-packages/scapy/arch/common.py", line 156, in compile_filter
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req or type mgt subtype auth or type mgt subtype assoc-req or type mgt subtype reassoc-req (-1)
2023-11-08 15:42:51,425 [INFO] fakeap.py: try running with --no_bpf_filters
2023-11-08 15:42:52,221 [WARNING] fakeap.py: beacon(): network is down or no such device (wlan0mon) ... exiting ...
```

**Software and hardware:**

 - OS: Debian 11 bullseye
 - Hardware: NEO2
 - Profiler version: 1.0.15

**Comment by joshschmelzle** [comment]
The scapy exception failing to compile filters is due to a problem with the version of libpcap shipped in 2.1.2 (libpcap0.8:arm64 1.10.0-2). 

This can be resolved on a WLAN Pi running 2.1.2 by installing a newer version of libpcap (libpcap0.8=1.10.3-1~bpo11+1). Thanks @adriangranados for the find.

```bash
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req or type mgt subtype auth or type mgt subtype assoc-req or type mgt subtype reassoc-req (-1)
2023-11-08 15:42:51,425 [INFO] fakeap.py: try running with --no_bpf_filters
2023-11-08 15:42:52,221 [WARNING] fakeap.py: beacon(): network is down or no such device (wlan0mon) ... exiting ...
wlanpi@wlanpi:~$ sudo apt-get install libpcap0.8=1.10.3-1~bpo11+1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  libpcap0.8
1 upgraded, 0 newly installed, 0 to remove and 79 not upgraded.
Need to get 157 kB of archives.
After this operation, 14.3 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye-backports/main arm64 libpcap0.8 arm64 1.10.3-1~bpo11+1 [157 kB]
Fetched 157 kB in 0s (421 kB/s)
(Reading database ... 65451 files and directories currently installed.)
Preparing to unpack .../libpcap0.8_1.10.3-1~bpo11+1_arm64.deb ...
Unpacking libpcap0.8:arm64 (1.10.3-1~bpo11+1) over (1.10.0-2) ...
Setting up libpcap0.8:arm64 (1.10.3-1~bpo11+1) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+deb11u6) ...
wlanpi@wlanpi:~$ sudo profiler

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting a fake AP using wlan0mon on channel 36 (5180)

Getting started:

 - Associate your Wi-Fi client to *our* SSID: WLAN Pi
 - Enter any random password to connect
 - Authentication will fail, which is OK
 - We should receive an association request to 78:d2:94:2c:05:47
 - Results are then saved locally and printed on the shell
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2023-11-08 15:44:27,708 [INFO] fakeap.py: starting beacon transmissions
```
